// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rodzaj_wydatku2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rodzaj_wydatku2));
        
        string IMigrationMetadata.Id
        {
            get { return "201405052356022_rodzaj_wydatku2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
