// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class usuniecie_tabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuniecie_tabel));
        
        string IMigrationMetadata.Id
        {
            get { return "201406021857118_usuniecie_tabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
