// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class size_dormularzK1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(size_dormularzK1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241358453_size_dormularzK1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
