// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class foreign_keys3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreign_keys3));
        
        string IMigrationMetadata.Id
        {
            get { return "201405051226573_foreign_keys3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
