// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mergeContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergeContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201405041851392_mergeContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
