// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rodzaj_wydatku : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rodzaj_wydatku));
        
        string IMigrationMetadata.Id
        {
            get { return "201405052344028_rodzaj_wydatku"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
