// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201405042042467_newTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
