// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class not_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(not_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201406021921106_not_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
