// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class foreign_keys1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreign_keys1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405181020275_foreign_keys1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
