// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class size_dziedzina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(size_dziedzina));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241357336_size_dziedzina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
