// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class size2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(size2));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241349011_size2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
