// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class size_K1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(size_K1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241400562_size_K1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
