// <auto-generated />
namespace WnioskiOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class org1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(org1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241421085_org1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
